### ISSUE TITLE
Unknown layer type: Normalize

### ISSUE THREAD

**Issue by imistyrain** [runhang/caffe-ssd-windows#1]
I build ssd_detect sucessfully, but when run the demo, I got this error:
F1022 01:32:05.517215 10012 layer_factory.cpp:77] Check failed: registry.count(t
ype) == 1 (0 vs. 1) Unknown layer type: Normalize (known types: AnnotatedData, B
atchNorm, Bias, Concat, Convolution, DetectionEvaluate, DetectionOutput, Eltwise
, Flatten, Input, LRN, MemoryData, MultiBoxLoss, Permute, Pooling, Power, PriorB
ox, Python, ReLU, Reshape, Scale, Sigmoid, SmoothL1Loss, Softmax, SoftmaxWithLos
s, Split, TanH)
*** Check failure stack trace: ***

**Comment by eric612** [comment]
I fixed this bug at my fork project :  https://github.com/eric612/caffe-ssd-windows , 
Add following function at layer_factory.cpp
  // Get normalize layer according to engine.
  template <typename Dtype>
  shared_ptr<Layer<Dtype> > GetNormalizeLayer(const LayerParameter& param) {
	return shared_ptr<Layer<Dtype> >(new NormalizeLayer<Dtype>(param));
  }
  REGISTER_LAYER_CREATOR(Normalize, GetNormalizeLayer); 

remove REGISTER_LAYER_CLASS(Normalize);  // (normalize_layer.cpp, Line 232)

**Comment by runhang** [comment]
@imistyrain I apologized that It was not until now that I read the mail.  @eric612  The answer is correct. 
 Thank you for your answer, I will fix this bug.
