### ISSUE TITLE
Unknow data layer type "Slice"

### ISSUE THREAD

**Issue by StrugglingForBetter** [runhang/caffe-ssd-windows#3]
Unknow data layer type "Slice"

请问如何解决这个问题？

谢谢！

**Comment by runhang** [comment]
You can fixed this bug at this code,
// 在 layer_factory.cpp添加一下内容
// Get Slice layer according to engine.
template
shared_ptr GetSliceLayer(const LayerParameter& param) {
return shared_ptr(new SliceLayer(param));
}
REGISTER_LAYER_CREATOR(Slice, GetSliceLayer);

// 定位到 slice_layer.cpp 第122行
REGISTER_LAYER_CLASS(Slice); // 将该段代码注释掉

**Comment by StrugglingForBetter** [comment]
@runhang 谢谢回复！我可以试试，请问可以给一个你的个人联系方式吗？微信，qq，常用邮箱都可以，关于这个库，我还有很多问题需要请教，github上挺难做到及时

**Comment by runhang** [comment]
VX: 378175931

**Comment by StrugglingForBetter** [comment]
@runhang 按照你说的修改了，编译报错：
E:\caffe_ssd_windows\src\caffe\layer_factory.cpp(201): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [E:\caffe_ssd_w
indows\scripts\build\src\caffe\caffe.vcxproj]
E:\caffe_ssd_windows\src\caffe\layer_factory.cpp(201): error C2146: 语法错误: 缺少“;”(在标识符“DetectionOutput”的前面) [E:\caffe_ssd
_windows\scripts\build\src\caffe\caffe.vcxproj]
E:\caffe_ssd_windows\src\caffe\layer_factory.cpp(203): error C2065: “Dtype”: 未声明的标识符 [E:\caffe_ssd_windows\scripts\buil
d\src\caffe\caffe.vcxproj]
E:\caffe_ssd_windows\src\caffe\layer_factory.cpp(203): error C2923: “caffe::Layer”: 对于参数“Dtype”，“Dtype”不是有效的 模板 类型变量 [E
:\caffe_ssd_windows\scripts\build\src\caffe\caffe.vcxproj]
E:\caffe_ssd_windows\src\caffe\layer_factory.cpp(203): error C3203: “Layer”: 未专用化的 类 模板 不能用作 模板 变量，该变量属于 模板 参数“T”，应为 re
al 类型 [E:\caffe_ssd_windows\scripts\build\src\caffe\caffe.vcxproj]
E:\caffe_ssd_windows\src\caffe\layer_factory.cpp(203): error C2143: 语法错误: 缺少“;”(在“{”的前面) [E:\caffe_ssd_windows\scripts\
build\src\caffe\caffe.vcxproj]
E:\caffe_ssd_windows\src\caffe\layer_factory.cpp(203): error C2447: “{”: 缺少函数标题(是否是老式的形式表?) [E:\caffe_ssd_windows\scrip
ts\build\src\caffe\caffe.vcxproj]
E:\caffe_ssd_windows\src\caffe\layer_factory.cpp(206): error C2065: “GetDetectionOutputLayer”: 未声明的标识符 [E:\caffe_ssd_wi
ndows\scripts\build\src\caffe\caffe.vcxproj]
E:\caffe_ssd_windows\src\caffe\layer_factory.cpp(206): error C2062: 意外的类型“float” [E:\caffe_ssd_windows\scripts\build\sr
c\caffe\caffe.vcxproj]
E:\caffe_ssd_windows\src\caffe\layer_factory.cpp(206): error C2062: 意外的类型“double” [E:\caffe_ssd_windows\scripts\build\s
rc\caffe\caffe.vcxproj]
